In [1]:
import numpy as np
import pandas as pd

In [33]:
ac=pd.read_csv(r'G:\Data Science\Kanav Assignments\Sample EDA\a.csv')
ac.head(1)
##Doubt-path not accepted.placed r infornt.no issues in analysing and manupalting file?

,Unnamed: 0,ID,Salary,DOJ,DOL,Designation,JobCity,Gender,DOB,10percentage,...,ComputerScience,MechanicalEngg,ElectricalEngg,TelecomEngg,CivilEngg,conscientiousness,agreeableness,extraversion,nueroticism,openess_to_experience
0,train,203097,420000.0,6/1/12 0:00,present,senior quality engineer,Bangalore,f,2/19/90 0:00,84.3,...,-1,-1,-1,-1,-1,0.9737,0.8128,0.5269,1.3549,-0.4455

In [3]:
ac.describe(include='all')

,Unnamed: 0,ID,Salary,DOJ,DOL,Designation,JobCity,Gender,DOB,10percentage,...,ComputerScience,MechanicalEngg,ElectricalEngg,TelecomEngg,CivilEngg,conscientiousness,agreeableness,extraversion,nueroticism,openess_to_experience
count,3998,3.998000e+03,3.998000e+03,3998,3998,3998,3998,3998,3998,3998.000000,...,3998.000000,3998.000000,3998.000000,3998.000000,3998.000000,3998.000000,3998.000000,3998.000000,3998.000000,3998.000000
unique,1,NaN,NaN,81,67,419,339,2,1872,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,train,NaN,NaN,7/1/14 0:00,present,software engineer,Bangalore,m,1/1/91 0:00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,3998,NaN,NaN,199,1875,539,627,3041,11,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,6.637945e+05,3.076998e+05,NaN,NaN,NaN,NaN,NaN,NaN,77.925443,...,90.742371,22.974737,16.478739,31.851176,2.683842,-0.037831,0.146496,0.002763,-0.169033,-0.138110
std,NaN,3.632182e+05,2.127375e+05,NaN,NaN,NaN,NaN,NaN,NaN,9.850162,...,175.273083,98.123311,87.585634,104.852845,36.658505,1.028666,0.941782,0.951471,1.007580,1.008075
min,NaN,1.124400e+04,3.500000e+04,NaN,NaN,NaN,NaN,NaN,NaN,43.000000,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-4.126700,-5.781600,-4.600900,-2.643000,-7.375700
25%,NaN,3.342842e+05,1.800000e+05,NaN,NaN,NaN,NaN,NaN,NaN,71.680000,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-0.713525,-0.287100,-0.604800,-0.868200,-0.669200
50%,NaN,6.396000e+05,3.000000e+05,NaN,NaN,NaN,NaN,NaN,NaN,79.150000,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,0.046400,0.212400,0.091400,-0.234400,-0.094300
75%,NaN,9.904800e+05,3.700000e+05,NaN,NaN,NaN,NaN,NaN,NaN,85.670000,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,0.702700,0.812800,0.672000,0.526200,0.502400
max,NaN,1.298275e+06,4.000000e+06,NaN,NaN,NaN,NaN,NaN,NaN,97.760000,...,715.000000,623.000000,676.000000,548.000000,516.000000,1.995300,1.904800,2.535400,3.352500,1.822400

# Observation-1

In [115]:
ac[['10percentage','12percentage','collegeGPA','CollegeTier']][ac['Salary']>ac['Salary'].mean()]

      10percentage  12percentage  collegeGPA  CollegeTier
0            84.30         95.80       78.00            2
1            85.40         85.00       70.06            2
2            85.00         68.20       70.00            2
3            85.60         83.60       74.64            1
7            92.00         91.00        8.58            1
8            90.00         91.20       85.03            1
10           88.60         83.70       74.90            2
11           81.00         86.00       72.29            1
15           69.54         64.43       63.00            2
16           85.80         74.80       64.80            2
19           79.00         62.20       76.30            2
20           91.20         84.63       78.15            2
24           88.00         90.00       76.00            2
25           86.80         82.80       78.00            2
26           90.88         82.50       66.15            2
30           84.00         92.00       77.20            2
31           77.20         86.10       71.00            2
32           87.00         84.40       79.30            1
35           85.00         61.00       64.98            2
38           52.33         67.00       77.15            2
42           91.40         73.00       71.00            1
44           84.50         82.50       92.10            2
48           86.60         75.00       74.00            2
52           85.20         81.50       57.64            2
53           89.25         78.00       80.00            2
57           89.88         95.40       80.80            2
64           78.00         83.00       72.13            1
65           89.37         79.00       70.00            2
66           90.00         94.40       76.12            2
67           81.00         79.00       71.50            2
...            ...           ...         ...          ...
3928         58.17         64.31       65.33            2
3930         83.60         73.40       61.80            2
3932         91.00         94.40       82.40            2
3933         87.00         90.60       69.04            2
3944         91.30         81.00       80.30            2
3946         73.00         61.50       75.80            2
3950         84.00         71.83       61.32            2
3954         88.40         92.90       69.37            2
3956         86.00         96.00       79.98            2
3958         79.90         89.40       77.15            2
3959         89.60         86.20       85.00            2
3961         84.20         69.20       65.00            2
3965         85.33         54.83       80.90            2
3966         89.60         67.00       75.37            2
3968         81.00         75.60       73.86            2
3969         76.00         89.80       62.00            2
3970         82.80         89.20       75.00            2
3971         81.00         77.00       77.00            2
3973         66.85         59.11       82.10            2
3977         62.00         61.00       60.00            2
3978         89.70         86.70       80.00            2
3979         69.16         65.66       77.50            1
3983         88.10         91.10       68.20            2
3984         89.80         83.80       70.00            2
3985         90.40         87.00       77.00            2
3990         88.00         88.00       73.00            2
3991         80.00         70.00       66.00            2
3992         73.00         54.00       79.00            2
3995         81.86         65.50       70.00            2
3997         70.60         68.00       68.00            2

[1799 rows x 4 columns]

# Observation-2

In [39]:
sd=ac.groupby('Gender')
sd.head(2)

,Unnamed: 0,ID,Salary,DOJ,DOL,Designation,JobCity,Gender,DOB,10percentage,...,ComputerScience,MechanicalEngg,ElectricalEngg,TelecomEngg,CivilEngg,conscientiousness,agreeableness,extraversion,nueroticism,openess_to_experience
0,train,203097,420000.0,6/1/12 0:00,present,senior quality engineer,Bangalore,f,2/19/90 0:00,84.3,...,-1,-1,-1,-1,-1,0.9737,0.8128,0.5269,1.3549,-0.4455
1,train,579905,500000.0,9/1/13 0:00,present,assistant manager,Indore,m,10/4/89 0:00,85.4,...,-1,-1,-1,-1,-1,-0.7335,0.3789,1.2396,-0.1076,0.8637
2,train,810601,325000.0,6/1/14 0:00,present,systems engineer,Chennai,f,8/3/92 0:00,85.0,...,-1,-1,-1,-1,-1,0.2718,1.7109,0.1637,-0.8682,0.6721
3,train,267447,1100000.0,7/1/11 0:00,present,senior software engineer,Gurgaon,m,12/5/89 0:00,85.6,...,-1,-1,-1,-1,-1,0.0464,0.3448,-0.3440,-0.4078,-0.9194

In [43]:
ac['Gender'].value_counts()

m    3041
f     957
Name: Gender, dtype: int64

In [40]:
sd['Salary'].mean()

Gender
f    294937.304075
m    311716.211772
Name: Salary, dtype: float64

# Obervation-3

In [45]:
dc=ac.groupby('JobCity')
dc.head(1)

,Unnamed: 0,ID,Salary,DOJ,DOL,Designation,JobCity,Gender,DOB,10percentage,...,ComputerScience,MechanicalEngg,ElectricalEngg,TelecomEngg,CivilEngg,conscientiousness,agreeableness,extraversion,nueroticism,openess_to_experience
0,train,203097,420000.0,6/1/12 0:00,present,senior quality engineer,Bangalore,f,2/19/90 0:00,84.30,...,-1,-1,-1,-1,-1,0.9737,0.8128,0.5269,1.35490,-0.4455
1,train,579905,500000.0,9/1/13 0:00,present,assistant manager,Indore,m,10/4/89 0:00,85.40,...,-1,-1,-1,-1,-1,-0.7335,0.3789,1.2396,-0.10760,0.8637
2,train,810601,325000.0,6/1/14 0:00,present,systems engineer,Chennai,f,8/3/92 0:00,85.00,...,-1,-1,-1,-1,-1,0.2718,1.7109,0.1637,-0.86820,0.6721
3,train,267447,1100000.0,7/1/11 0:00,present,senior software engineer,Gurgaon,m,12/5/89 0:00,85.60,...,-1,-1,-1,-1,-1,0.0464,0.3448,-0.3440,-0.40780,-0.9194
4,train,343523,200000.0,3/1/14 0:00,3/1/15 0:00,get,Manesar,m,2/27/91 0:00,78.00,...,-1,-1,-1,-1,-1,-0.8810,-0.2793,-1.0697,0.09163,-0.1295
5,train,1027655,300000.0,6/1/14 0:00,present,system engineer,Hyderabad,m,7/2/92 0:00,89.92,...,407,-1,-1,-1,-1,-0.3027,-0.6201,-2.2954,-0.74150,-0.8608
6,train,947847,300000.0,8/1/14 0:00,5/1/15 0:00,java software engineer,Banglore,m,2/1/93 0:00,86.08,...,346,-1,-1,-1,-1,1.7081,-0.1054,-1.0379,-2.00920,-1.0872
8,train,552574,600000.0,7/1/13 0:00,present,electrical engineer,Noida,m,9/17/91 0:00,90.00,...,-1,-1,-1,-1,-1,-0.1590,0.5454,-0.6048,-0.74150,-0.2859
9,train,1203363,230000.0,7/1/14 0:00,present,project engineer,Kolkata,m,6/13/93 0:00,77.00,...,-1,-1,-1,-1,-1,-1.3080,0.5454,-0.9122,0.90660,0.0973
11,train,190393,450000.0,8/1/11 0:00,10/1/14 0:00,senior systems engineer,Pune,m,2/10/90 0:00,81.00,...,-1,-1,-1,-1,-1,-2.2720,1.1248,0.8171,-0.40780,-0.4455
15,train,536517,350000.0,8/1/13 0:00,present,network engineer,-1,f,1/17/90 0:00,69.54,...,-1,-1,-1,-1,-1,1.7465,1.9048,0.6720,-0.29020,1.2528
35,train,942679,350000.0,3/1/14 0:00,present,online marketing manager,mohali,f,9/15/90 0:00,85.00,...,-1,-1,-1,-1,-1,-0.4854,-0.5213,2.1129,-0.73500,1.8224
40,train,245887,120000.0,6/1/11 0:00,3/1/12 0:00,site manager,Jhansi,m,5/4/89 0:00,66.60,...,-1,286,-1,-1,-1,-0.4173,0.3448,0.0914,-0.40780,0.6603
41,train,955678,145000.0,7/1/14 0:00,9/1/14 0:00,software developer,Delhi,m,4/21/92 0:00,75.00,...,346,-1,-1,-1,-1,-0.8772,-1.1196,-1.0659,-1.24860,-1.4356
43,train,1207660,120000.0,4/1/14 0:00,4/1/15 0:00,.net developer,Hyderabad,m,7/5/93 0:00,59.00,...,-1,-1,-1,-1,-1,-0.0154,-2.4516,-0.4511,0.27270,-3.1602
44,train,247617,380000.0,5/1/12 0:00,4/1/15 0:00,programmer analyst,Bangalore,f,1/6/89 0:00,84.50,...,-1,-1,-1,-1,-1,0.5100,0.6568,-0.6343,0.29730,0.1864
46,train,592833,205000.0,7/1/13 0:00,4/1/15 0:00,jr. software engineer,noida,f,9/24/91 0:00,85.60,...,253,-1,-1,-1,-1,0.1282,0.5454,0.1637,-0.48790,0.8637
47,train,434621,95000.0,10/1/12 0:00,10/1/13 0:00,software developer,delhi,m,2/1/92 0:00,69.60,...,-1,-1,-1,-1,-1,-0.4173,0.6568,-0.7794,1.70740,0.1864
50,train,245337,60000.0,6/1/11 0:00,2/1/13 0:00,trainee software developer,Bhubaneswar,f,2/13/88 0:00,66.50,...,-1,-1,-1,-1,-1,-1.0355,0.0328,-2.2308,1.00240,0.3444
52,train,794209,400000.0,4/1/15 0:00,present,software engineer,Navi Mumbai,m,3/9/92 0:00,85.20,...,-1,-1,-1,-1,-1,1.1336,0.3789,1.0859,0.65300,0.2889
53,train,1082717,350000.0,9/1/14 0:00,present,assistant system engineer,Mumbai,m,8/6/91 0:00,89.25,...,-1,-1,484,-1,-1,-0.1590,-0.1206,-0.6048,-1.62890,-1.4356
54,train,764522,120000.0,11/1/14 0:00,present,android developer,New Delhi,f,1/14/92 0:00,58.40,...,-1,-1,-1,-1,-1,0.3350,0.0924,-0.6582,-0.48210,-0.1543
55,train,989860,250000.0,8/1/14 0:00,present,software engineer,Mangalore,m,2/13/92 0:00,90.80,...,376,-1,-1,-1,-1,-0.3027,0.7119,-0.2974,1.16010,-0.4776
56,train,416752,240000.0,3/1/13 0:00,present,customer service,Rewari,f,7/15/89 0:00,78.00,...,-1,-1,-1,-1,-1,0.8192,-0.0842,-0.5980,-0.64280,-0.6035
58,train,1063642,200000.0,6/1/13 0:00,1/1/14 0:00,project engineer,Gaziabaad,m,3/27/90 0:00,63.30,...,-1,-1,-1,-1,-1,-1.0208,-0.6201,-0.2974,-0.10760,-1.2440
63,train,636871,150000.0,10/1/14 0:00,4/1/15 0:00,management trainee,Bhiwadi,m,1/10/92 0:00,60.66,...,-1,446,-1,-1,-1,-2.2351,-2.6847,-2.6028,0.39950,-5.4770
65,train,1044453,310000.0,2/1/14 0:00,5/1/14 0:00,system engineer,Mysore,m,12/2/90 0:00,89.37,...,-1,-1,-1,-1,-1,0.9900,1.2114,-0.2974,-1.12180,1.2470
71,train,1089599,250000.0,5/1/14 0:00,present,java software engineer,Rajkot,m,12/3/90 0:00,86.00,...,500,-1,-1,-1,-1,1.1336,1.3779,2.1617,-0.99500,1.0554
73,train,982400,240000.0,6/1/14 0:00,4/1/15 0:00,android developer,Greater Noida,m,7/6/92 0:00,75.00,...,-1,-1,-1,-1,-1,-0.1590,0.8784,1.2396,0.27270,-0.6692
83,train,836060,145000.0,6/1/14 0:00,8/1/14 0:00,customer service representative,Jaipur,m,11/23/93 0:00,80.00,...,-1,-1,-1,-1,-1,0.1282,-0.1206,0.9322,1.54040,0.0973
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3599,train,305011,240000.0,8/1/11 0:00,6/1/12 0:00,qa analyst,Yamuna Nagar,m,7/24/89 0:00,60.00,...,-1,-1,-1,-1,-1,-0.4173,0.8128,-0.3440,0.41480,0.3444
3614,train,666254,215000.0,8/1/13 0:00,1/1/14 0:00,quality assurance engineer,shahibabad,m,6/17/93 0:00,68.83,...,-1,446,-1,-1,-1,0.4155,1.0449,0.4711,0.52620,0.6721
3618,train,960142,240000.0,11/1/14 0:00,present,assistant manager,sampla,m,7/17/92 0:00,68.40,...,-1,-1,-1,420,-1,0.2718,1.3779,0.3174,-0.23440,1.0554
3621,train,141813,175000.0,12/1/10 0:00,11/1/14 0:00,system administrator,Guwahati,m,1/31/86 0:00,70.50,...,-1,-1,-1,-1,-1,0.3555,-0.1232,0.6720,1.94240,-0.2875
3636,train,326938,120000.0,9/1/11 0:00,12/1/12 0:00,web developer,Rourkela,f,8/15/90 0:00,78.00,...,-1,-1,-1,-1,-1,0.5100,-0.2012,-0.2714,0.41483,-0.1295
3642,train,812555,150000.0,10/1/13 0:00,present,java software engineer,Banaglore,m,10/11/90 0:00,85.00,...,-1,-1,-1,-1,-1,1.7081,0.2124,2.0080,-2.38950,1.2470
3648,train,260350,200000.0,6/1/11 0:00,9/1/12 0:00,lecturer,Vellore,f,6/12/89 0:00,93.20,...,-1,-1,-1,-1,-1,-1.9770,-3.3994,-0.3149,0.95530,-1.5513
3671,train,50241,120000.0,8/1/10 0:00,6/1/12 0:00,lecturer,Dausa,m,10/20/89 0:00,83.00,...,-1,-1,-1,-1,-1,-0.1082,0.3448,0.8171,-0.29020,0.8183
3693,train,133328,170000.0,9/1/12 0:00,1/1/13 0:00,bss engineer,latur (Maharashtra ),m,6/1/88 0:00,54.40,...,-1,-1,-1,-1,-1,0.0464,0.6568,0.2366,-0.05520,0.5024
3730,train,982188,205000.0,2/1/15 0:00,present,programmer,NEW DELHI,m,8/10/91 0:00,80.00,...,407,-1,-1,-1,-1,-1.1644,0.7119,1.3933,-1.62890,1.4386
3761,train,628193,215000.0,8/1/13 0:00,present,sales coordinator,kanpur,m,2/17/91 0:00,69.60,...,-1,-1,-1,393,-1,0.7027,0.0459,-1.6807,-0.61470,-0.8608
3799,train,355322,240000.0,7/1/13 0:00,present,computer faculty,Mainpuri,m,6/3/91 0:00,71.50,...,-1,-1,-1,-1,-1,0.5100,1.1248,-0.7794,-0.26090,-0.6035
3819,train,959820,180000.0,9/1/14 0:00,present,business development manager,karnal,f,3/19/91 0:00,89.60,...,376,-1,-1,-1,-1,-1.4517,-0.6201,-0.4511,0.65300,-1.0524
3823,train,918568,775000.0,8/1/14 0:00,present,mechanical design engineer,Dammam,m,1/12/91 0:00,87.40,...,-1,469,-1,-1,-1,-0.8772,-0.1206,-0.1437,-0.23440,-0.0943
3832,train,625434,565000.0,10/1/13 0:00,4/1/15 0:00,engineer,Haldia,m,10/28/91 0:00,92.83,...,-1,-1,660,-1,-1,0.1282,0.0459,-0.1437,-0.23440,0.0973
3845,train,282011,550000.0,7/1/11 0:00,11/1/14 0:00,engineering technician,sambalpur,f,6/25/90 0:00,70.30,...,-1,473,-1,-1,-1,-0.2628,0.8128,1.3977,1.00240,0.3444
3858,train,989810,180000.0,9/1/14 0:00,7/1/15 0:00,network engineer,RAE BARELI,m,8/9/92 0:00,83.00,...,376,-1,-1,-1,-1,0.8463,0.8784,1.2396,-0.99500,0.2889
3865,train,1095963,300000.0,8/1/14 0:00,present,design engineer,ranchi,m,10/29/92 0:00,82.87,...,-1,-1,-1,-1,292,-0.4463,-1.1196,-0.9122,1.16010,-2.2021
3868,train,618243,320000.0,6/1/13 0:00,present,project engineer,jAipur,m,9/14/91 0:00,87.40,...,-1,-1,-1,-1,388,0.5591,-0.6201,0.0100,-1.12180,-2.5853
3882,train,1110880,105000.0,8/1/14 0:00,present,software developer,BANGLORE,m,3/15/91 0:00,75.00,...,346,-1,-1,-1,-1,-1.1644,-1.2861,-0.6048,0.01920,-1.2440
3890,train,844474,195000.0,10/1/13 0:00,5/1/15 0:00,software developer,Patiala,m,8/13/92 0:00,69.00,...,-1,-1,-1,-1,-1,0.4155,0.2124,0.4711,-0.74150,0.6721
3891,train,262863,240000.0,7/1/14 0:00,present,lecturer,Gorakhpur,m,11/19/90 0:00,56.00,...,-1,-1,-1,-1,-1,-0.8810,1.5928,0.0914,0.88480,0.9763
3934,train,335328,200000.0,7/1/13 0:00,12/1/14 0:00,service manager,new dehli,m,1/11/91 0:00,76.00,...,-1,-1,-1,366,-1,-0.0696,0.5008,-0.6343,-0.26087,-0.9194
3935,train,450793,200000.0,2/1/13 0:00,2/1/14 0:00,sql developer,BANGALORE,m,2/20/90 0:00,78.40,...,-1,-1,-1,-1,-1,-0.2628,0.7348,-1.5776,0.76730,-0.4455
3947,train,1107633,180000.0,7/1/13 0:00,present,php developer,Ambala City,m,12/15/92 0:00,64.40,...,-1,-1,-1,-1,-1,-0.0154,0.3789,0.4711,-0.10760,0.2889
3951,train,885459,145000.0,5/1/14 0:00,present,mechanical engineer,Karad,m,8/27/92 0:00,93.07,...,-1,407,-1,-1,-1,-0.3027,-1.4526,-0.2974,1.28690,-1.4356
3961,train,230702,700000.0,7/1/11 0:00,9/1/14 0:00,planning engineer,Rajpura,m,12/27/87 0:00,84.20,...,-1,-1,-1,-1,460,-1.3447,0.0328,-2.3759,-0.99530,0.3444
3963,train,509245,200000.0,8/1/13 0:00,present,research engineer,Pilani,m,10/3/90 0:00,74.33,...,-1,-1,-1,-1,-1,0.7419,0.6568,-0.4891,0.26790,-0.7615
3980,train,197796,150000.0,7/1/11 0:00,7/1/12 0:00,get,haryana,m,8/5/86 0:00,84.00,...,-1,473,-1,-1,-1,-1.4992,0.5008,-0.9245,-0.64280,-0.6035
3996,train,947111,200000.0,7/1/14 0:00,1/1/15 0:00,software developer,Asifabadbanglore,f,3/20/92 0:00,78.72,...,438,-1,-1,-1,-1,-0.1590,0.0459,-0.4511,-0.36120,-0.0943

In [48]:
dc['Salary'].mean()[(dc['JobCity']=='Hyderabad') & (dc['Gender']=='m')]

335000.0

# Observation-4

In [114]:
lc=ac.loc[(ac['10percentage']>80.0) & (ac['12percentage']>80.0) &(ac['collegeGPA']>75.0),'conscientiousness':'openess_to_experience']
print(lc.mean())

lc

conscientiousness        0.117981
agreeableness            0.317892
extraversion            -0.037166
nueroticism             -0.347883
openess_to_experience   -0.116553
dtype: float64

,conscientiousness,agreeableness,extraversion,nueroticism,openess_to_experience
0,0.9737,0.8128,0.5269,1.35490,-0.4455
5,-0.3027,-0.6201,-2.2954,-0.74150,-0.8608
8,-0.1590,0.5454,-0.6048,-0.74150,-0.2859
20,-0.1082,0.9688,0.5269,-0.29020,0.3444
22,-0.4463,-0.6201,-0.6048,0.77980,-2.7769
24,0.4155,0.8027,0.1357,-0.99500,-0.6692
25,0.0464,1.2028,-0.9245,0.53230,-0.2875
30,-0.4173,0.6568,-0.0537,-1.23030,-0.9194
32,-0.7335,-0.4536,-1.0659,1.16010,-0.4776
39,0.3941,1.2808,0.2366,-2.19980,-0.4455
44,0.5100,0.6568,-0.6343,0.29730,0.1864
45,-0.5899,-1.1196,0.4711,-0.74150,-1.4356
57,0.3555,-0.2793,-0.6343,-0.29020,-0.2875
61,1.8517,1.5444,0.3174,0.39950,0.6721
66,-0.2628,-0.1232,0.0914,-1.23030,-0.1295
70,-1.4517,-1.4526,-1.2196,1.79400,-2.3937
76,-0.4173,0.9688,-0.1988,-0.29020,0.3049
79,0.5591,-0.4536,0.0100,-0.48790,0.6721
95,0.6646,1.4368,-0.0537,0.88483,0.5024
164,-1.0208,1.0449,-1.3733,-1.88240,1.0554
166,-1.3447,0.6178,-1.4688,0.88483,0.6603
169,0.9900,0.7119,1.0859,-0.10760,0.6721
182,-0.1590,0.5454,-0.4511,1.54040,0.4805
187,0.5100,1.1248,0.5269,0.00353,0.1864
197,0.1282,-0.6201,0.0100,0.77980,-0.8608
198,-0.7335,0.0459,-1.2196,-0.23440,-1.0524
200,-1.0355,0.9688,-1.0697,0.17980,-0.6035
206,-0.0154,0.2124,-0.1437,-0.74150,0.6721
208,0.6646,1.1248,1.5428,-0.40780,0.3444
209,1.4208,0.8784,0.7785,-0.10760,0.8637
...,...,...,...,...,...
3766,0.5591,0.2124,-0.6048,-0.86820,0.0973
3772,1.7081,0.8784,0.0100,-1.37530,0.0973
3773,-0.7335,0.5454,1.3933,0.52620,1.0554
3778,-0.3027,-0.4536,-2.6028,0.77980,0.2889
3781,-1.0355,0.1888,-0.0537,0.41480,0.6603
3782,-0.7335,0.0459,-0.1437,1.03330,-0.8608
3792,-0.5719,1.5928,0.5269,-0.17270,0.1864
3824,-0.3014,0.5008,-0.4891,-0.17277,-0.4455
3839,1.5644,0.5454,-0.2974,-1.37530,1.0554
3841,1.5644,0.7119,1.5470,-2.13600,-0.0943
3849,0.1282,0.5454,-0.4511,-1.62890,0.6721
3851,-0.4173,-0.5523,-0.7068,-0.40780,-0.2875
3859,0.1282,0.7119,0.4711,-0.99500,1.0554
3868,0.5591,-0.6201,0.0100,-1.12180,-2.5853
3871,0.6646,0.8518,-0.2714,-1.23027,0.3444
3879,-0.8772,-1.2861,0.7785,-0.36120,-0.8608
3880,-1.3080,0.2124,1.3933,2.93490,0.4805
3889,0.1282,0.3789,-1.5270,-0.86820,-0.6692
3894,-1.1644,-1.1196,0.1637,0.52620,-2.2021
3907,0.2782,0.5008,-1.0697,0.53230,0.1864
3912,-1.3447,-1.0593,0.6720,1.00240,-1.7093
3932,-1.1128,0.6568,-0.6343,2.03060,-1.5513
3937,0.1623,0.0328,-0.3440,-1.05410,0.5024
3944,1.2828,1.7878,-0.3803,0.17980,0.3444
3948,-0.1590,-0.7866,-1.0659,-0.74150,-1.2440
3956,0.1282,-0.8320,-1.2056,0.90660,-1.3590
3959,-0.1590,0.7119,0.9322,-0.74150,0.2889
3978,0.2718,1.2114,0.4711,-0.10760,0.8637
3985,0.2782,0.3448,0.0914,-1.14220,-0.6035
3994,-0.3027,0.8784,0.9322,0.77980,-0.0943

# Observation-5

In [130]:
ac.loc[ac['CollegeTier']==1,'English':'Quant']

      English  Logical  Quant
3         635      585    625
7         545      555    590
8         615      670    530
11        495      605    715
32        570      475    295
36        380      535    530
42        555      560    825
64        444      555    695
137       535      445    465
158       590      555    545
163       420      485    545
164       625      605    735
165       565      475    615
166       625      555    625
168       530      595    340
184       525      525    565
193       525      455    465
195       580      640    870
196       595      605    645
198       660      680    765
200       655      625    675
206       730      610    695
214       455      485    605
220       660      495    590
227       695      625    725
229       720      580    645
230       640      570    840
249       595      520    605
268       650      570    750
283       370      525    545
...       ...      ...    ...
3539      485      485    565
3545      595      695    575
3562      515      685    635
3585      660      510    780
3597      405      425    405
3598      464      505    505
3613      435      435    575
3620      580      455    485
3654      510      545    570
3677      625      560    620
3701      465      445    425
3705      570      580    800
3707      605      455    685
3733      605      585    580
3765      520      425    485
3766      710      570    635
3785      650      605    545
3795      485      510    590
3801      465      495    450
3814      605      520    530
3823      580      555    410
3856      495      395    585
3864      615      670    765
3894      615      655    665
3900      475      500    635
3912      545      525    715
3913      720      570    515
3914      545      400    385
3972      650      445    475
3979      395      435    645

[297 rows x 3 columns]